baseURL: 'https://tsic.top/'
languageCode: 'zh-CN'
title: "Tsic's Blog"
pagination.pagerSize: 5
theme: "papermod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
minify:
    disableXML: true

taxonomies:
    tag: "tags"
    category: "categories"
    series: "series"

menu:
    main:
        - name: 全部
          url: post
          weight: 5
        - name: 标签
          url: tags
          weight: 10
        - name: 搜索
          url: search
          weight: 15

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Tsic's Blog - https://tsic.top"
    author: tsic404
    defaultTheme: dark
    ShowShareButtons: true
    ShowReadingTime: true

    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    comments: true

    profileMode:
        enabled: true
        title: "Tsic's Blog"
        subtitle: "Tsic's detial"
        imageUrl: "https://avatars.githubusercontent.com/u/48748112?v=4"
        imageTitle: "Tsic"
        imageWidth: 120
        imageHeight: 120

        buttons:
            - name: 全部
              url: post
            - name: 标签
              url: tags
            - name: 分类
              url: categories
            - name: 系列
              url: series

    socialIcons:
        - name: github
          url: "https://github.com/tsic404"
        - name: Telegram
          url: "https://t.me/tsic404"
        - name: Rss
          url: "index.xml"
  
    editPost:
        URL: "https://github.com/tsic404/blog/tree/master/content"
        Text: "编辑" # edit text
        appendFilePath: true # to append file path to Edit link

    assets:
        disableHLJS: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
